### ISSUE TITLE
Controller Issue: listing.controllers.js

### ISSUE THREAD

**Issue by instinger** [instinger/website#1]
The updateListing function of the controller is hitting error of 401 "you are not authorised"

**Comment by gm-gautam12** [comment]
The user._id is returning as an object Id but listing.userRef is in string format.

you can change the modification to :
 if(req.user._id.toString() !== listing.userRef)

**Comment by gm-gautam12** [comment]
Hey can i be a contributer of this repo

**Comment by instinger** [comment]
successful pr will surely do the job
